-- Create users table (extension of Supabase Auth)
CREATE TABLE public.users (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    email TEXT UNIQUE NOT NULL,
    avatar_url TEXT,
    country TEXT,
    favorite_food TEXT,
    community_score INTEGER DEFAULT 0,
    role TEXT DEFAULT 'user' CHECK (role IN ('user', 'admin')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create categories table
CREATE TABLE public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    icon_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create restaurants table
CREATE TABLE public.restaurants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    address TEXT NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    price_range TEXT CHECK (price_range IN ('$', '$$', '$$$', '$$$$')),
    rating DECIMAL(3,2) DEFAULT 0,
    review_count INTEGER DEFAULT 0,
    operating_hours JSONB,
    phone_number TEXT,
    social_media_source TEXT, -- tiktok, instagram, etc
    post_url TEXT,
    popularity_score INTEGER DEFAULT 0,
    is_hidden_gem BOOLEAN DEFAULT false,
    is_trending BOOLEAN DEFAULT false,
    is_approved BOOLEAN DEFAULT false,
    last_updated TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Junction table for restaurants and categories
CREATE TABLE public.restaurant_categories (
    restaurant_id BIGINT REFERENCES public.restaurants ON DELETE CASCADE,
    category_id BIGINT REFERENCES public.categories ON DELETE CASCADE,
    PRIMARY KEY (restaurant_id, category_id)
);

-- Restaurant images
CREATE TABLE public.restaurant_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id BIGINT REFERENCES public.restaurants ON DELETE CASCADE,
    image_url TEXT NOT NULL,
    is_primary BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Restaurant menu
CREATE TABLE public.restaurant_menu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id BIGINT REFERENCES public.restaurants ON DELETE CASCADE,
    item_name TEXT NOT NULL,
    price DECIMAL(10,2),
    description TEXT,
    image_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Reviews table
CREATE TABLE public.reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.users ON DELETE CASCADE NOT NULL,
    restaurant_id BIGINT REFERENCES public.restaurants ON DELETE CASCADE NOT NULL,
    rating INTEGER CHECK (rating >= 1 AND rating <= 5),
    content TEXT,
    waiting_time_minutes INTEGER,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Community posts
CREATE TABLE public.posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.users ON DELETE CASCADE NOT NULL,
    restaurant_id BIGINT REFERENCES public.restaurants ON DELETE SET NULL,
    content TEXT,
    media_urls TEXT[], -- array of image/video urls
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Comments on posts
CREATE TABLE public.comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT REFERENCES public.posts ON DELETE CASCADE NOT NULL,
    user_id UUID REFERENCES public.users ON DELETE CASCADE NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Likes on posts
CREATE TABLE public.likes (
    post_id BIGINT REFERENCES public.posts ON DELETE CASCADE NOT NULL,
    user_id UUID REFERENCES public.users ON DELETE CASCADE NOT NULL,
    PRIMARY KEY (post_id, user_id)
);

-- Bookmarks (Saved restaurants or posts)
CREATE TABLE public.bookmarks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.users ON DELETE CASCADE NOT NULL,
    restaurant_id BIGINT REFERENCES public.restaurants ON DELETE CASCADE,
    post_id BIGINT REFERENCES public.posts ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Achievements
CREATE TABLE public.achievements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    description TEXT,
    icon_url TEXT,
    points INTEGER DEFAULT 0
);

-- User achievements
CREATE TABLE public.user_achievements (
    user_id UUID REFERENCES public.users ON DELETE CASCADE NOT NULL,
    achievement_id BIGINT REFERENCES public.achievements ON DELETE CASCADE NOT NULL,
    unlocked_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (user_id, achievement_id)
);

-- Journeys (Stats tracking)
CREATE TABLE public.journeys (
    user_id UUID REFERENCES public.users ON DELETE CASCADE PRIMARY KEY,
    restaurants_visited INTEGER DEFAULT 0,
    cities_explored INTEGER DEFAULT 0,
    reviews_written INTEGER DEFAULT 0,
    photos_uploaded INTEGER DEFAULT 0,
    distance_travelled DECIMAL(10,2) DEFAULT 0,
    favorite_cuisine TEXT
);

-- Reports
CREATE TABLE public.reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id UUID REFERENCES public.users ON DELETE SET NULL,
    post_id BIGINT REFERENCES public.posts ON DELETE CASCADE,
    review_id BIGINT REFERENCES public.reviews ON DELETE CASCADE,
    reason TEXT NOT NULL,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'resolved', 'dismissed')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Notifications
CREATE TABLE public.notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.users ON DELETE CASCADE NOT NULL,
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    payload JSONB,
    is_read BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Row Level Security (RLS)
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.restaurants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
-- Add more RLS policies as needed

-- Policies for users
CREATE POLICY "Public users are viewable by everyone." ON public.users FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile." ON public.users FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile." ON public.users FOR UPDATE USING (auth.uid() = id);

-- Policies for restaurants
CREATE POLICY "Restaurants are viewable by everyone." ON public.restaurants FOR SELECT USING (true);
CREATE POLICY "Only admins can insert/update restaurants." ON public.restaurants FOR ALL USING (
    EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'admin')
);

-- Policies for posts
CREATE POLICY "Posts are viewable by everyone." ON public.posts FOR SELECT USING (true);
CREATE POLICY "Users can create posts." ON public.posts FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update/delete own posts." ON public.posts FOR ALL USING (auth.uid() = user_id);

-- Function to increment community score
CREATE OR REPLACE FUNCTION increment_community_score(row_id UUID, increment_by INTEGER)
RETURNS void AS $$
BEGIN
  UPDATE public.users
  SET community_score = community_score + increment_by
  WHERE id = row_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
