-- ============================================================================
-- Social-media ingestion pipeline: raw staging layer
-- ----------------------------------------------------------------------------
-- Apify (TikTok / Instagram) scraper output is a stream of *social posts*, not
-- structured restaurants. We land every raw record here losslessly, then a
-- separate enrichment step (LLM extraction + geocoding) promotes qualifying
-- rows into public.restaurants with is_approved = false for admin review.
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.scraped_posts (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Source identity / dedup key
    platform               TEXT NOT NULL DEFAULT 'tiktok',
    web_video_url          TEXT NOT NULL,              -- Apify: webVideoUrl (unique per post)
    author_name            TEXT,                       -- Apify: authorMeta.name

    -- Content
    caption                TEXT,                       -- Apify: text
    cover_url              TEXT,                       -- Apify: videoMeta.coverUrl (SIGNED, expires!)
    hashtags               JSONB,                      -- Apify: hashtags[]

    -- Engagement metrics
    digg_count             INTEGER DEFAULT 0,          -- Apify: diggCount (likes)
    share_count            INTEGER DEFAULT 0,          -- Apify: shareCount
    play_count             INTEGER DEFAULT 0,          -- Apify: playCount (views)
    comment_count          INTEGER DEFAULT 0,          -- Apify: commentCount
    video_duration         INTEGER DEFAULT 0,          -- Apify: videoMeta.duration
    is_ad                  BOOLEAN DEFAULT false,      -- Apify: isAd

    posted_at              TIMESTAMPTZ,                -- Apify: createTimeISO

    -- Full original record so enrichment can be re-run without re-scraping
    raw                    JSONB NOT NULL,

    -- Processing state machine
    status                 TEXT NOT NULL DEFAULT 'pending'
                             CHECK (status IN ('pending','processing','promoted','skipped','failed')),
    extraction             JSONB,                      -- structured venue guess from the LLM
    extraction_confidence  NUMERIC(3,2),               -- 0.00 - 1.00 from the LLM
    promoted_restaurant_id BIGINT REFERENCES public.restaurants ON DELETE SET NULL,
    error                  TEXT,                       -- last failure reason, if any

    ingested_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    processed_at           TIMESTAMPTZ,

    CONSTRAINT scraped_posts_web_video_url_key UNIQUE (web_video_url)
);

CREATE INDEX IF NOT EXISTS idx_scraped_posts_status ON public.scraped_posts (status);

-- ----------------------------------------------------------------------------
-- Restaurant provenance / dedup
-- ----------------------------------------------------------------------------
-- Track which scraped post a restaurant originated from so a re-run does not
-- create duplicates. post_url already exists on public.restaurants; enforce it.
CREATE UNIQUE INDEX IF NOT EXISTS idx_restaurants_post_url
    ON public.restaurants (post_url)
    WHERE post_url IS NOT NULL;

-- ----------------------------------------------------------------------------
-- Row Level Security: staging is admin-only, never public
-- ----------------------------------------------------------------------------
ALTER TABLE public.scraped_posts ENABLE ROW LEVEL SECURITY;

-- Admins can read/manage staging rows from the app (service_role bypasses RLS
-- entirely, which is what the Edge Functions use).
DROP POLICY IF EXISTS "Admins can view scraped posts." ON public.scraped_posts;
CREATE POLICY "Admins can view scraped posts." ON public.scraped_posts
    FOR SELECT USING (
        EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'admin')
    );

DROP POLICY IF EXISTS "Admins can manage scraped posts." ON public.scraped_posts;
CREATE POLICY "Admins can manage scraped posts." ON public.scraped_posts
    FOR ALL USING (
        EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'admin')
    );
