-- 20260808000002_admin_audit_log.sql
--
-- Creates an audit trail for administrator actions on user accounts.
-- Every update, status toggle, or other privileged action is recorded
-- so operators can review who changed what and when.

-- ─── 1. Table ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.admin_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- The admin who performed the action (references auth.users).
    admin_user_id UUID REFERENCES auth.users ON DELETE SET NULL,
    admin_username TEXT,

    -- What happened, e.g. 'update_user', 'toggle_account_status'.
    action TEXT NOT NULL,

    -- The affected user row.
    target_user_id UUID REFERENCES public.users ON DELETE SET NULL,
    target_username TEXT,

    -- Semi-structured diff: { "field": {"from": ..., "to": ...} }
    field_changes JSONB DEFAULT '{}'::jsonb,

    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ─── 2. Indexes ──────────────────────────────────────────────────────
-- Speed up chronological review and look-ups by target user.
CREATE INDEX IF NOT EXISTS idx_admin_audit_log_created_at
  ON public.admin_audit_log (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_admin_audit_log_target_user
  ON public.admin_audit_log (target_user_id);
CREATE INDEX IF NOT EXISTS idx_admin_audit_log_action
  ON public.admin_audit_log (action);

-- ─── 3. RLS ──────────────────────────────────────────────────────────
ALTER TABLE public.admin_audit_log ENABLE ROW LEVEL SECURITY;

-- Admins can insert audit records (the application inserts on their behalf).
DROP POLICY IF EXISTS "Admins can insert audit logs" ON public.admin_audit_log;
CREATE POLICY "Admins can insert audit logs"
  ON public.admin_audit_log FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.users
      WHERE id = auth.uid() AND role = 'admin'
    )
  );

-- Admins can read all audit records.
DROP POLICY IF EXISTS "Admins can view audit logs" ON public.admin_audit_log;
CREATE POLICY "Admins can view audit logs"
  ON public.admin_audit_log FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.users
      WHERE id = auth.uid() AND role = 'admin'
    )
  );

-- ─── 4. Grants ───────────────────────────────────────────────────────
GRANT INSERT ON public.admin_audit_log TO authenticated;
GRANT SELECT ON public.admin_audit_log TO authenticated;
